import Foundation

// MARK: - Gatherings
extension SampleData {

    // Stable gathering IDs
    static let gatheringIdPho         = "g-00000001-pho-cooking"
    static let gatheringIdKoreanMovie = "g-00000002-korean-movie"
    static let gatheringIdHoli        = "g-00000003-holi-festival"
    static let gatheringIdArabicCoffee = "g-00000004-arabic-coffee"
    static let gatheringIdLatinDance  = "g-00000005-latin-dance"
    static let gatheringIdMandarin    = "g-00000006-mandarin-study"
    static let gatheringIdGardenWalk  = "g-00000007-garden-walk"
    static let gatheringIdEthiopian   = "g-00000008-ethiopian-dinner"
    static let gatheringIdKaraoke     = "g-00000009-karaoke-night"
    static let gatheringIdPotluck     = "g-00000010-mixed-potluck"
    static let gatheringIdJollof      = "g-00000011-jollof-workshop"
    static let gatheringIdKpop        = "g-00000012-kpop-dance"

    static let gatherings: [Gathering] = [
        // 1. Vietnamese Pho Cooking Class — upcoming (2 days)
        Gathering(
            id: gatheringIdPho,
            hostId: hostLinhTran.id,
            title: "Vietnamese Pho Cooking Class",
            description: "Learn to make authentic pho from scratch! We will cover the broth, noodle selection, and all the toppings. Both chicken and beef options available. All dietary needs accommodated.",
            templateType: .food,
            emoji: "🍜",
            imageURL: URL(string: "https://picsum.photos/seed/pho-cooking/400/250"),
            city: "Melbourne",
            school: "University of Melbourne",
            locationName: "Student Kitchen, Level 2, Union House",
            latitude: -37.7983,
            longitude: 144.9610,
            startsAt: cal(.day, 2),
            endsAt: cal(.day, 2, hour: 3),
            maxAttendees: 12,
            visibility: .matchingTags,
            vibe: .lowKey,
            status: .upcoming,
            isDraft: false,
            tags: ["Vietnamese", "Cooking"],
            attendeeCount: 8,
            attendeeAvatars: ["🌿", "⭐", "🔥", "🌙", "🍊"],
            hostName: "Linh Tran",
            hostAvatarEmoji: "🌸",
            hostRating: 4.8,
            isBookmarked: false,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -5)
        ),
        // 2. Korean Movie Night: Parasite — upcoming (3 days)
        Gathering(
            id: gatheringIdKoreanMovie,
            hostId: userIdJin,
            title: "Korean Movie Night: Parasite",
            description: "Grab some popcorn and join us for a screening of Bong Joon-ho's masterpiece. We will have Korean snacks and a post-movie discussion. English subtitles provided.",
            templateType: .hangout,
            emoji: "🎬",
            imageURL: URL(string: "https://picsum.photos/seed/korean-movie/400/250"),
            city: "Melbourne",
            school: "Monash University",
            locationName: "Campus Centre Theatre, Clayton",
            latitude: -37.9105,
            longitude: 145.1362,
            startsAt: cal(.day, 3),
            endsAt: cal(.day, 3, hour: 3),
            maxAttendees: 25,
            visibility: .open,
            vibe: .hype,
            status: .upcoming,
            isDraft: false,
            tags: ["Korean", "Film"],
            attendeeCount: 15,
            attendeeAvatars: ["⭐", "🌿", "🔥", "💜", "🦋"],
            hostName: "Jin Park",
            hostAvatarEmoji: "⭐",
            hostRating: 4.6,
            isBookmarked: true,
            isJoined: false,
            isMaybe: false,
            createdAt: cal(.day, -4)
        ),
        // 3. Holi Festival Celebration — upcoming (5 days)
        Gathering(
            id: gatheringIdHoli,
            hostId: userIdPriya,
            title: "Holi Festival Celebration",
            description: "Come celebrate the festival of colours with us! We will have organic colours, traditional music, dancing, and a feast of Indian street food. Wear white clothes you do not mind getting colourful!",
            templateType: .cultural,
            emoji: "🎨",
            imageURL: URL(string: "https://picsum.photos/seed/holi-festival/400/250"),
            city: "Melbourne",
            school: "RMIT University",
            locationName: "Alumni Courtyard, RMIT City Campus",
            latitude: -37.8081,
            longitude: 144.9631,
            startsAt: cal(.day, 5),
            endsAt: cal(.day, 5, hour: 5),
            maxAttendees: 50,
            visibility: .open,
            vibe: .hype,
            status: .upcoming,
            isDraft: false,
            tags: ["Indian", "Festivals"],
            attendeeCount: 30,
            attendeeAvatars: ["🔥", "🌿", "⭐", "🌙", "🍊"],
            hostName: "Priya Sharma",
            hostAvatarEmoji: "🔥",
            hostRating: 4.9,
            isBookmarked: false,
            isJoined: false,
            isMaybe: false,
            createdAt: cal(.day, -10)
        ),
        // 4. Arabic Coffee & Conversation — upcoming (4 days)
        Gathering(
            id: gatheringIdArabicCoffee,
            hostId: userIdAmira,
            title: "Arabic Coffee & Conversation",
            description: "A cosy afternoon learning about Arabic coffee traditions. We will brew traditional qahwa together and practise conversational Arabic phrases. All levels welcome, no experience needed.",
            templateType: .food,
            emoji: "☕",
            imageURL: URL(string: "https://picsum.photos/seed/arabic-coffee/400/250"),
            city: "Melbourne",
            school: "Deakin University",
            locationName: "Building LA, Level 3 Common Room, Burwood",
            latitude: -37.8483,
            longitude: 145.1148,
            startsAt: cal(.day, 4),
            endsAt: cal(.day, 4, hour: 2),
            maxAttendees: 8,
            visibility: .matchingTags,
            vibe: .lowKey,
            status: .upcoming,
            isDraft: false,
            tags: ["Middle Eastern", "Language Exchange"],
            attendeeCount: 5,
            attendeeAvatars: ["🌙", "🌿", "🌺", "✨", "🌊"],
            hostName: "Amira Hassan",
            hostAvatarEmoji: "🌙",
            hostRating: 4.7,
            isBookmarked: false,
            isJoined: false,
            isMaybe: false,
            createdAt: cal(.day, -3)
        ),
        // 5. Latin Dance Social — upcoming (tomorrow), almost full
        Gathering(
            id: gatheringIdLatinDance,
            hostId: userIdCarlos,
            title: "Latin Dance Social",
            description: "Salsa, bachata, and merengue! No partner needed, all levels welcome. We will start with a beginner lesson then open the floor. Bring water and your dancing shoes!",
            templateType: .active,
            emoji: "💃",
            imageURL: URL(string: "https://picsum.photos/seed/latin-dance/400/250"),
            city: "Melbourne",
            school: "La Trobe University",
            locationName: "Sports Hall B, Bundoora Campus",
            latitude: -37.7209,
            longitude: 145.0486,
            startsAt: cal(.day, 1),
            endsAt: cal(.day, 1, hour: 3),
            maxAttendees: 20,
            visibility: .open,
            vibe: .hype,
            status: .upcoming,
            isDraft: false,
            tags: ["Latin American", "Dancing"],
            attendeeCount: 18,
            attendeeAvatars: ["🍊", "🌿", "🔥", "⭐", "🦋"],
            hostName: "Carlos Mendez",
            hostAvatarEmoji: "🍊",
            hostRating: 4.8,
            isBookmarked: true,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -7)
        ),
        // 6. Mandarin Study Group — upcoming (6 days)
        Gathering(
            id: gatheringIdMandarin,
            hostId: userIdWei,
            title: "Mandarin Study Group",
            description: "Weekly Mandarin practice session for intermediate learners. We will work through HSK 4 vocabulary, practise conversation, and help each other with tones. Bring your textbook!",
            templateType: .study,
            emoji: "📖",
            imageURL: URL(string: "https://picsum.photos/seed/mandarin-study/400/250"),
            city: "Melbourne",
            school: "University of Melbourne",
            locationName: "Baillieu Library, Group Study Room 4",
            latitude: -37.7986,
            longitude: 144.9597,
            startsAt: cal(.day, 6),
            endsAt: cal(.day, 6, hour: 2),
            maxAttendees: 10,
            visibility: .matchingTags,
            vibe: .chill,
            status: .upcoming,
            isDraft: false,
            tags: ["Chinese", "Study"],
            attendeeCount: 4,
            attendeeAvatars: ["🌊", "🌿", "🌺", "🌙"],
            hostName: "Wei Chen",
            hostAvatarEmoji: "🌊",
            hostRating: 4.5,
            isBookmarked: false,
            isJoined: false,
            isMaybe: false,
            createdAt: cal(.day, -2)
        ),
        // 7. Japanese Garden Walk & Tea — past (3 days ago), was full
        Gathering(
            id: gatheringIdGardenWalk,
            hostId: userIdYuki,
            title: "Japanese Garden Walk & Tea",
            description: "A peaceful morning walk through the Japanese section of the Royal Botanic Gardens followed by a traditional tea ceremony. Limited spots to keep it intimate.",
            templateType: .cultural,
            emoji: "🍵",
            imageURL: URL(string: "https://picsum.photos/seed/garden-walk/400/250"),
            city: "Melbourne",
            school: "University of Melbourne",
            locationName: "Royal Botanic Gardens, Gate D Entrance",
            latitude: -37.8304,
            longitude: 144.9796,
            startsAt: cal(.day, -3),
            endsAt: cal(.day, -3, hour: 3),
            maxAttendees: 10,
            visibility: .matchingTags,
            vibe: .welcoming,
            status: .completed,
            isDraft: false,
            tags: ["Japanese", "Meditation"],
            attendeeCount: 10,
            attendeeAvatars: ["🌺", "🌿", "⭐", "🔥", "🌙"],
            hostName: "Yuki Tanaka",
            hostAvatarEmoji: "🌺",
            hostRating: 4.9,
            isBookmarked: false,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -14)
        ),
        // 8. Ethiopian Dinner & Stories — past (7 days ago)
        Gathering(
            id: gatheringIdEthiopian,
            hostId: userIdAbel,
            title: "Ethiopian Dinner & Stories",
            description: "An evening of Ethiopian culture. We will cook injera and several wot dishes together, then eat communally while sharing stories from our cultures. Vegetarian options included.",
            templateType: .food,
            emoji: "🫓",
            imageURL: URL(string: "https://picsum.photos/seed/ethiopian-dinner/400/250"),
            city: "Melbourne",
            school: "Monash University",
            locationName: "International House Kitchen, Clayton",
            latitude: -37.9112,
            longitude: 145.1340,
            startsAt: cal(.day, -7),
            endsAt: cal(.day, -7, hour: 4),
            maxAttendees: 15,
            visibility: .open,
            vibe: .welcoming,
            status: .completed,
            isDraft: false,
            tags: ["African", "Food Tours"],
            attendeeCount: 12,
            attendeeAvatars: ["💜", "🌿", "⭐", "🍊", "✨"],
            hostName: "Abel Tesfaye",
            hostAvatarEmoji: "💜",
            hostRating: 4.7,
            isBookmarked: false,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -18)
        ),
        // 9. Filipino Karaoke Night — past (10 days ago)
        Gathering(
            id: gatheringIdKaraoke,
            hostId: userIdMaria,
            title: "Filipino Karaoke Night",
            description: "The ultimate karaoke experience! Filipino hospitality meets power ballads. Snacks provided, song requests open. Prepare your best rendition of your favourite hits.",
            templateType: .hangout,
            emoji: "🎤",
            imageURL: URL(string: "https://picsum.photos/seed/karaoke-night/400/250"),
            city: "Melbourne",
            school: "RMIT University",
            locationName: "Building 80, Level 4 Common Room",
            latitude: -37.8080,
            longitude: 144.9635,
            startsAt: cal(.day, -10),
            endsAt: cal(.day, -10, hour: 4),
            maxAttendees: 12,
            visibility: .open,
            vibe: .hype,
            status: .completed,
            isDraft: false,
            tags: ["Filipino", "Music"],
            attendeeCount: 8,
            attendeeAvatars: ["🦋", "🌿", "⭐", "🔥", "🍊"],
            hostName: "Maria Santos",
            hostAvatarEmoji: "🦋",
            hostRating: 4.8,
            isBookmarked: false,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -20)
        ),
        // 10. Mixed Culture Potluck — upcoming (10 days), hosted by Mai (current user!)
        Gathering(
            id: gatheringIdPotluck,
            hostId: userIdMai,
            title: "Mixed Culture Potluck",
            description: "Bring a dish from your culture and share the story behind it! This is a relaxed evening to try new foods and learn about each other's backgrounds. Everyone is welcome.",
            templateType: .food,
            emoji: "🫕",
            imageURL: URL(string: "https://picsum.photos/seed/mixed-potluck/400/250"),
            city: "Melbourne",
            school: "University of Melbourne",
            locationName: "Graduate House Dining Room",
            latitude: -37.7993,
            longitude: 144.9585,
            startsAt: cal(.day, 10),
            endsAt: cal(.day, 10, hour: 4),
            maxAttendees: 20,
            visibility: .matchingTags,
            vibe: .welcoming,
            status: .upcoming,
            isDraft: false,
            tags: ["Cooking", "Festivals"],
            attendeeCount: 7,
            attendeeAvatars: ["🌿", "⭐", "🌙", "🍊", "💜"],
            hostName: "Mai Nguyen",
            hostAvatarEmoji: "🌿",
            hostRating: 4.6,
            isBookmarked: false,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -1)
        ),
        // 11. Nigerian Jollof Rice Workshop — past (14 days ago)
        Gathering(
            id: gatheringIdJollof,
            hostId: userIdSade,
            title: "Nigerian Jollof Rice Workshop",
            description: "Learn the secrets of authentic Nigerian jollof rice from a true expert. We will settle the great jollof debate once and for all. Taste-testing mandatory!",
            templateType: .food,
            emoji: "🍚",
            imageURL: URL(string: "https://picsum.photos/seed/jollof-workshop/400/250"),
            city: "Melbourne",
            school: "Deakin University",
            locationName: "Building LB, Kitchen Space, Burwood",
            latitude: -37.8478,
            longitude: 145.1155,
            startsAt: cal(.day, -14),
            endsAt: cal(.day, -14, hour: 3),
            maxAttendees: 8,
            visibility: .matchingTags,
            vibe: .welcoming,
            status: .completed,
            isDraft: false,
            tags: ["Nigerian", "Cooking"],
            attendeeCount: 6,
            attendeeAvatars: ["✨", "🌿", "🔥", "💜", "🦋"],
            hostName: "Sade Okafor",
            hostAvatarEmoji: "✨",
            hostRating: 4.9,
            isBookmarked: false,
            isJoined: true,
            isMaybe: false,
            createdAt: cal(.day, -21)
        ),
        // 12. K-pop Dance Workshop — upcoming (8 days)
        Gathering(
            id: gatheringIdKpop,
            hostId: userIdJin,
            title: "K-pop Dance Workshop",
            description: "Learn the choreography to the latest K-pop hits! We will break down moves step by step. No dance experience needed, just bring energy and comfortable clothes.",
            templateType: .active,
            emoji: "🕺",
            imageURL: URL(string: "https://picsum.photos/seed/kpop-dance/400/250"),
            city: "Melbourne",
            school: "Monash University",
            locationName: "Sports Recreation Centre, Studio 2",
            latitude: -37.9115,
            longitude: 145.1350,
            startsAt: cal(.day, 8),
            endsAt: cal(.day, 8, hour: 2),
            maxAttendees: 15,
            visibility: .open,
            vibe: .hype,
            status: .upcoming,
            isDraft: false,
            tags: ["Korean", "Dancing"],
            attendeeCount: 12,
            attendeeAvatars: ["⭐", "🌿", "🔥", "🦋", "🍊"],
            hostName: "Jin Park",
            hostAvatarEmoji: "⭐",
            hostRating: 4.6,
            isBookmarked: false,
            isJoined: false,
            isMaybe: false,
            createdAt: cal(.day, -2)
        ),
    ]

    // MARK: - Gathering Members (for Pho Cooking Class)

    static let gatheringMembers: [GatheringMember] = [
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: hostLinhTran.id,
            status: .joined,
            joinedAt: cal(.day, -5),
            userName: "Linh Tran",
            userAvatarEmoji: "🌸",
            sharedTags: ["Vietnamese", "Cooking"]
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdMai,
            status: .joined,
            joinedAt: cal(.day, -4),
            userName: "Mai Nguyen",
            userAvatarEmoji: "🌿",
            sharedTags: ["Vietnamese", "Cooking"]
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdJin,
            status: .joined,
            joinedAt: cal(.day, -4),
            userName: "Jin Park",
            userAvatarEmoji: "⭐",
            sharedTags: ["Cooking"]
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdPriya,
            status: .joined,
            joinedAt: cal(.day, -3),
            userName: "Priya Sharma",
            userAvatarEmoji: "🔥",
            sharedTags: ["Cooking"]
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdAmira,
            status: .joined,
            joinedAt: cal(.day, -3),
            userName: "Amira Hassan",
            userAvatarEmoji: "🌙",
            sharedTags: []
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdCarlos,
            status: .joined,
            joinedAt: cal(.day, -2),
            userName: "Carlos Mendez",
            userAvatarEmoji: "🍊",
            sharedTags: ["Cooking"]
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdYuki,
            status: .maybe,
            joinedAt: cal(.day, -2),
            userName: "Yuki Tanaka",
            userAvatarEmoji: "🌺",
            sharedTags: []
        ),
        GatheringMember(
            gatheringId: gatheringIdPho,
            userId: userIdMaria,
            status: .joined,
            joinedAt: cal(.day, -1),
            userName: "Maria Santos",
            userAvatarEmoji: "🦋",
            sharedTags: ["Cooking"]
        ),
    ]

    // MARK: - Hosting Templates

    static let hostingTemplates: [HostingTemplate] = [
        HostingTemplate(
            id: "template-food",
            title: "Food",
            systemImage: "fork.knife",
            emoji: "🍜",
            description: "Cook, eat, and bond over food from your culture",
            defaultTags: ["Food", "Cooking"],
            defaultMaxAttendees: 6,
            defaultVisibility: .matchingTags,
            defaultVibe: .lowKey
        ),
        HostingTemplate(
            id: "template-study",
            title: "Study",
            systemImage: "book.fill",
            emoji: "📖",
            description: "Study sessions, language exchange, or tutoring",
            defaultTags: ["Study"],
            defaultMaxAttendees: 8,
            defaultVisibility: .matchingTags,
            defaultVibe: .chill
        ),
        HostingTemplate(
            id: "template-hangout",
            title: "Hangout",
            systemImage: "party.popper.fill",
            emoji: "🎉",
            description: "Movie nights, game nights, and casual hangs",
            defaultTags: ["Low-key hangout"],
            defaultMaxAttendees: 8,
            defaultVisibility: .open,
            defaultVibe: .hype
        ),
        HostingTemplate(
            id: "template-cultural",
            title: "Cultural",
            systemImage: "globe.asia.australia.fill",
            emoji: "🌍",
            description: "Festivals, traditions, and cultural celebrations",
            defaultTags: ["Festivals"],
            defaultMaxAttendees: 10,
            defaultVisibility: .matchingTags,
            defaultVibe: .welcoming
        ),
        HostingTemplate(
            id: "template-faith",
            title: "Faith",
            systemImage: "hands.sparkles.fill",
            emoji: "🙏",
            description: "Prayer groups, meditation, and spiritual gatherings",
            defaultTags: ["Faith", "Meditation"],
            defaultMaxAttendees: 12,
            defaultVisibility: .inviteOnly,
            defaultVibe: .welcoming
        ),
        HostingTemplate(
            id: "template-active",
            title: "Active",
            systemImage: "figure.run",
            emoji: "⚽",
            description: "Sports, dance, hiking, and outdoor activities",
            defaultTags: ["Sports", "Dancing"],
            defaultMaxAttendees: 15,
            defaultVisibility: .open,
            defaultVibe: .hype
        ),
    ]

    // MARK: - Private Helpers

    private static func cal(_ component: Calendar.Component, _ value: Int, hour extra: Int = 0) -> Date {
        let base = Calendar.current.date(byAdding: component, value: value, to: Date())!
        if extra == 0 { return base }
        return Calendar.current.date(byAdding: .hour, value: extra, to: base)!
    }
}
